baseurl: "https://www.philyeo.dev/"
title: PhilipYeo
#theme: ghostwriter
languageCode: en-us
copyright: Philip Yeo
googleAnalytics: G-YRXE6MJVJC
disqusShortname: XXX
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: My Name
  profile: ""

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: Philip Yeo
  description: "#!/bin/bash echo \"Hello World\""
  github: "https://github.com/philyeo"
  linkedin: "https://linkedin.com/in/philipyeo/"
  twitter: "https://twitter.com/philcp"
  opengraph: true
  shareTwitter: true
  rss: false
  shareFacebook: true
  shareLinkedIn: true
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""
  plausibleAnalytics:
    domain: ""
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL: ""

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: Projects
      url: /project/
      weight: 2
    - name: About
      url: /about/
      weight: 3

module:
  imports:
  - path: github.com/jbub/ghostwriter